"use client";

import { useEffect, useState } from "react";

type Language = "en" | "de" | "fr" | "es" | "it";
const languages: { code: Language; label: string }[] = [
  { code: "en", label: "EN" }, { code: "de", label: "DE" }, { code: "fr", label: "FR" }, { code: "es", label: "ES" }, { code: "it", label: "IT" },
];

const copy = {
  en: { nav: { approach: "Approach", vision: "Vision", access: "Early access", language: "Language" }, hero: { eyebrow: "European electric road travel", titleA: "Electric freedom.", titleB: "Beyond the road.", body: "We are exploring a new generation of premium electric motorhomes for Europe — thoughtfully selected, rigorously prepared, and made for the long way around.", cta: "Join early access", noteA: "Concept direction", noteB: "Not a commercial vehicle", scroll: "Scroll to explore" }, band: ["EUROPE", "ELECTRIC", "IN VALIDATION"], vision: { eyebrow: "A different kind of distance", titleA: "The open road", titleB: "is changing.", lead: "The next chapter of road travel will be quieter, more capable and more connected to the places it takes you.", body: "Northline is being built to help make that chapter real in Europe. We are currently validating technology, manufacturers and the route to market — before a single vehicle is offered." }, approach: { eyebrow: "The Northline approach", titleA: "From new energy", titleB: "to real freedom.", pillars: [{ title: "Electric by intent", copy: "Quiet, considered travel with the range and confidence to go further." }, { title: "Ready for Europe", copy: "A disciplined path through compliance, adaptation, support and service." }, { title: "Built around living", copy: "Thoughtful spaces for longer weekends, slower mornings and wider horizons." }] }, building: { eyebrow: "What we are building", titleA: "A trusted bridge between", titleB: "ambition and arrival.", lead: "The product is only part of the journey.", body: "We are investigating a complete European path: product selection at the source, adaptation for local use, homologation, transparent import, and the aftercare that makes ownership feel simple.", link: "Follow the journey" }, access: { eyebrow: "An early signal", titleA: "Be first to see", titleB: "what comes next.", body: "We are speaking with future owners, partners and people who believe road travel can be designed differently.", label: "Early access is opening soon", card: "Leave your interest and we will share the first validated concepts, availability and launch updates.", field: "Your email address", button: "Notify me", privacy: "No vehicle orders. No noise. Just the occasional meaningful update." }, footer: "Exploring the future of European road travel.", status: "A project in validation — 2026" },
  de: { nav: { approach: "Ansatz", vision: "Vision", access: "Frühzugang", language: "Sprache" }, hero: { eyebrow: "Elektrisches Reisen in Europa", titleA: "Elektrische Freiheit.", titleB: "Jenseits der Straße.", body: "Wir entwickeln eine neue Generation hochwertiger elektrischer Reisemobile für Europa — sorgfältig ausgewählt, gründlich vorbereitet und gemacht für den langen Weg.", cta: "Frühzugang sichern", noteA: "Konzeptphase", noteB: "Kein Serienfahrzeug", scroll: "Weiter entdecken" }, band: ["EUROPA", "ELEKTRISCH", "IN VALIDIERUNG"], vision: { eyebrow: "Eine andere Art von Weite", titleA: "Die offene Straße", titleB: "verändert sich.", lead: "Das nächste Kapitel des Reisens wird leiser, leistungsfähiger und stärker mit den Orten verbunden sein, die man entdeckt.", body: "Northline entsteht, um dieses Kapitel in Europa Wirklichkeit werden zu lassen. Wir prüfen derzeit Technologie, Hersteller und den Weg zum Markt — bevor ein Fahrzeug angeboten wird." }, approach: { eyebrow: "Der Northline-Ansatz", titleA: "Von neuer Energie", titleB: "zu echter Freiheit.", pillars: [{ title: "Elektrisch gedacht", copy: "Ruhiges, bewusstes Reisen mit Reichweite und Vertrauen für weitere Wege." }, { title: "Für Europa bereit", copy: "Ein klarer Weg durch Konformität, Anpassung, Support und Service." }, { title: "Für das Leben gebaut", copy: "Durchdachte Räume für lange Wochenenden, langsame Morgen und weite Horizonte." }] }, building: { eyebrow: "Was wir bauen", titleA: "Eine verlässliche Brücke zwischen", titleB: "Vision und Ankunft.", lead: "Das Produkt ist nur ein Teil der Reise.", body: "Wir untersuchen einen vollständigen europäischen Weg: Produktauswahl an der Quelle, Anpassung für den lokalen Einsatz, Homologation, transparenter Import und Betreuung, die Besitz einfach macht.", link: "Der Reise folgen" }, access: { eyebrow: "Ein erster Impuls", titleA: "Sehen Sie zuerst", titleB: "was als Nächstes kommt.", body: "Wir sprechen mit zukünftigen Besitzern, Partnern und Menschen, die glauben, dass Reisen anders gestaltet werden kann.", label: "Frühzugang öffnet bald", card: "Hinterlassen Sie Ihr Interesse. Wir teilen die ersten validierten Konzepte, Verfügbarkeiten und Updates.", field: "Ihre E-Mail-Adresse", button: "Benachrichtigen", privacy: "Keine Fahrzeugbestellung. Kein Lärm. Nur gelegentliche relevante Updates." }, footer: "Wir erkunden die Zukunft des europäischen Reisens.", status: "Ein Projekt in Validierung — 2026" },
  fr: { nav: { approach: "Approche", vision: "Vision", access: "Accès anticipé", language: "Langue" }, hero: { eyebrow: "Le voyage électrique en Europe", titleA: "La liberté électrique.", titleB: "Au-delà de la route.", body: "Nous explorons une nouvelle génération de camping-cars électriques haut de gamme pour l’Europe — sélectionnés avec soin, préparés avec rigueur et conçus pour aller plus loin.", cta: "Rejoindre l’accès anticipé", noteA: "Direction conceptuelle", noteB: "Pas un véhicule commercial", scroll: "Découvrir" }, band: ["EUROPE", "ÉLECTRIQUE", "EN VALIDATION"], vision: { eyebrow: "Une autre idée de la distance", titleA: "La route ouverte", titleB: "change.", lead: "Le prochain chapitre du voyage sera plus silencieux, plus capable et plus connecté aux lieux qu’il vous fait découvrir.", body: "Northline est créé pour donner vie à ce chapitre en Europe. Nous validons actuellement les technologies, les fabricants et la voie d’accès au marché — avant de proposer un seul véhicule." }, approach: { eyebrow: "L’approche Northline", titleA: "De la nouvelle énergie", titleB: "à la vraie liberté.", pillars: [{ title: "L’électrique par conviction", copy: "Un voyage calme et réfléchi, avec l’autonomie et la confiance pour aller plus loin." }, { title: "Prêt pour l’Europe", copy: "Une démarche rigoureuse : conformité, adaptation, assistance et service." }, { title: "Pensé pour vivre", copy: "Des espaces imaginés pour les longs week-ends, les matins tranquilles et les grands horizons." }] }, building: { eyebrow: "Ce que nous construisons", titleA: "Un pont de confiance entre", titleB: "l’ambition et l’arrivée.", lead: "Le produit n’est qu’une partie du voyage.", body: "Nous étudions un parcours européen complet : sélection à la source, adaptation à l’usage local, homologation, import transparent et accompagnement qui simplifie la propriété.", link: "Suivre l’aventure" }, access: { eyebrow: "Un premier signal", titleA: "Découvrez en premier", titleB: "la suite.", body: "Nous échangeons avec de futurs propriétaires, des partenaires et celles et ceux qui pensent que le voyage peut être conçu autrement.", label: "L’accès anticipé ouvre bientôt", card: "Manifestez votre intérêt. Nous partagerons les premiers concepts validés, les disponibilités et les actualités.", field: "Votre adresse e-mail", button: "Me prévenir", privacy: "Aucune commande. Aucun bruit. Seulement des nouvelles utiles, de temps en temps." }, footer: "Nous explorons l’avenir du voyage routier européen.", status: "Un projet en validation — 2026" },
  es: { nav: { approach: "Enfoque", vision: "Visión", access: "Acceso anticipado", language: "Idioma" }, hero: { eyebrow: "Viajes eléctricos por Europa", titleA: "Libertad eléctrica.", titleB: "Más allá de la carretera.", body: "Estamos explorando una nueva generación de autocaravanas eléctricas premium para Europa: seleccionadas con criterio, preparadas con rigor y hechas para llegar más lejos.", cta: "Unirme al acceso anticipado", noteA: "Dirección conceptual", noteB: "No es un vehículo comercial", scroll: "Descubrir" }, band: ["EUROPA", "ELÉCTRICO", "EN VALIDACIÓN"], vision: { eyebrow: "Otra forma de entender la distancia", titleA: "La carretera abierta", titleB: "está cambiando.", lead: "El próximo capítulo de los viajes será más silencioso, capaz y conectado con los lugares que te lleva a descubrir.", body: "Northline nace para hacer realidad ese capítulo en Europa. Ahora estamos validando tecnología, fabricantes y la ruta al mercado, antes de ofrecer un solo vehículo." }, approach: { eyebrow: "El enfoque Northline", titleA: "De la nueva energía", titleB: "a la libertad real.", pillars: [{ title: "Eléctrico por convicción", copy: "Viajes silenciosos y conscientes, con la autonomía y la confianza necesarias para llegar más lejos." }, { title: "Preparado para Europa", copy: "Un camino riguroso de conformidad, adaptación, soporte y servicio." }, { title: "Diseñado para vivir", copy: "Espacios pensados para fines de semana largos, mañanas lentas y horizontes amplios." }] }, building: { eyebrow: "Lo que estamos construyendo", titleA: "Un puente de confianza entre", titleB: "la ambición y la llegada.", lead: "El producto es solo una parte del viaje.", body: "Estamos estudiando un recorrido europeo completo: selección en origen, adaptación al uso local, homologación, importación transparente y un servicio posventa que simplifique la propiedad.", link: "Seguir el viaje" }, access: { eyebrow: "Una primera señal", titleA: "Sé el primero en ver", titleB: "lo que viene.", body: "Hablamos con futuros propietarios, socios y personas que creen que viajar por carretera puede diseñarse de otra manera.", label: "El acceso anticipado abrirá pronto", card: "Déjanos tu interés y compartiremos los primeros conceptos validados, disponibilidad y novedades.", field: "Tu dirección de email", button: "Avisarme", privacy: "No hay pedidos de vehículos. No hay ruido. Solo novedades relevantes de vez en cuando." }, footer: "Exploramos el futuro de los viajes por carretera en Europa.", status: "Un proyecto en validación — 2026" },
  it: { nav: { approach: "Approccio", vision: "Vision", access: "Accesso anticipato", language: "Lingua" }, hero: { eyebrow: "Viaggi elettrici in Europa", titleA: "Libertà elettrica.", titleB: "Oltre la strada.", body: "Stiamo esplorando una nuova generazione di motorhome elettrici premium per l’Europa — selezionati con cura, preparati con rigore e pensati per andare lontano.", cta: "Unisciti all’accesso anticipato", noteA: "Direzione concettuale", noteB: "Non è un veicolo commerciale", scroll: "Scopri" }, band: ["EUROPA", "ELETTRICO", "IN VALIDAZIONE"], vision: { eyebrow: "Un nuovo modo di vivere la distanza", titleA: "La strada aperta", titleB: "sta cambiando.", lead: "Il prossimo capitolo del viaggio sarà più silenzioso, capace e connesso ai luoghi che ti porta a scoprire.", body: "Northline nasce per rendere reale questo capitolo in Europa. Stiamo validando tecnologie, produttori e il percorso verso il mercato, prima di offrire un veicolo." }, approach: { eyebrow: "L’approccio Northline", titleA: "Dalla nuova energia", titleB: "alla libertà reale.", pillars: [{ title: "Elettrico per scelta", copy: "Viaggi silenziosi e consapevoli, con l’autonomia e la sicurezza per andare oltre." }, { title: "Pronto per l’Europa", copy: "Un percorso rigoroso tra conformità, adattamento, assistenza e servizio." }, { title: "Pensato per vivere", copy: "Spazi progettati per weekend lunghi, mattine lente e orizzonti aperti." }] }, building: { eyebrow: "Cosa stiamo costruendo", titleA: "Un ponte affidabile tra", titleB: "ambizione e arrivo.", lead: "Il prodotto è solo una parte del viaggio.", body: "Stiamo studiando un percorso europeo completo: selezione alla fonte, adattamento all’uso locale, omologazione, importazione trasparente e assistenza per rendere semplice la proprietà.", link: "Segui il viaggio" }, access: { eyebrow: "Un primo segnale", titleA: "Scopri per primo", titleB: "cosa viene dopo.", body: "Parliamo con futuri proprietari, partner e persone che credono che il viaggio su strada possa essere progettato diversamente.", label: "L’accesso anticipato apre presto", card: "Lascia il tuo interesse. Condivideremo i primi concept validati, disponibilità e aggiornamenti.", field: "Il tuo indirizzo email", button: "Avvisami", privacy: "Nessun ordine. Nessun rumore. Solo aggiornamenti utili, ogni tanto." }, footer: "Esploriamo il futuro dei viaggi su strada in Europa.", status: "Un progetto in validazione — 2026" },
} as const;

const catalogCopy = {
  en: { nav: "Catalog", eyebrow: "The first shortlist", titleA: "Real vehicles.", titleB: "Clear-eyed estimates.", intro: "A working shortlist of published Chinese models we are validating for a European route. Prices are indicative all-in estimates for Germany, not manufacturer quotes.", estimate: "Estimated all-in", specs: "Published specification", reference: "Interior reference — concept, not a production vehicle", source: "View manufacturer source", note: "Estimate includes a provisional allowance for transport, duties, adaptation, homologation, warranty reserve and 19% German VAT. Final classification, equipment and certification can move the number materially." },
  de: { nav: "Katalog", eyebrow: "Die erste Shortlist", titleA: "Echte Fahrzeuge.", titleB: "Klare Schätzungen.", intro: "Eine erste Auswahl veröffentlichter chinesischer Modelle, die wir für einen europäischen Weg prüfen. Die Preise sind indikative All-in-Schätzungen für Deutschland, keine Herstellerangebote.", estimate: "Geschätzter Gesamtpreis", specs: "Veröffentlichte Daten", reference: "Innenraum-Referenz — Konzept, kein Serienfahrzeug", source: "Herstellerquelle ansehen", note: "Die Schätzung enthält einen vorläufigen Ansatz für Transport, Zölle, Anpassung, Homologation, Garantie-Rücklage und 19 % deutsche MwSt. Klassifizierung, Ausstattung und Zertifizierung können den Betrag deutlich verändern." },
  fr: { nav: "Sélection", eyebrow: "La première sélection", titleA: "Des véhicules réels.", titleB: "Des estimations lucides.", intro: "Une première sélection de modèles chinois publiés que nous évaluons pour une voie européenne. Les prix sont des estimations indicatives tout compris pour l’Allemagne, pas des offres constructeur.", estimate: "Estimation tout compris", specs: "Données publiées", reference: "Référence intérieure — concept, pas un véhicule de série", source: "Voir la source constructeur", note: "L’estimation inclut une provision pour transport, droits, adaptation, homologation, garantie et TVA allemande de 19 %. La classification, l’équipement et la certification peuvent modifier fortement le montant." },
  es: { nav: "Catálogo", eyebrow: "La primera selección", titleA: "Vehículos reales.", titleB: "Estimaciones claras.", intro: "Una primera selección de modelos chinos publicados que estamos validando para una ruta europea. Los precios son estimaciones orientativas todo incluido para Alemania, no ofertas del fabricante.", estimate: "Estimación todo incluido", specs: "Datos publicados", reference: "Referencia de interior — concepto, no vehículo de producción", source: "Ver fuente del fabricante", note: "La estimación incluye una provisión para transporte, aranceles, adaptación, homologación, reserva de garantía y 19 % de IVA alemán. La clasificación, el equipamiento y la certificación pueden cambiar mucho la cifra." },
  it: { nav: "Catalogo", eyebrow: "La prima selezione", titleA: "Veicoli reali.", titleB: "Stime trasparenti.", intro: "Una prima selezione di modelli cinesi pubblicati che stiamo valutando per un percorso europeo. I prezzi sono stime indicative tutto compreso per la Germania, non offerte del produttore.", estimate: "Stima tutto compreso", specs: "Dati pubblicati", reference: "Riferimento interni — concept, non veicolo di serie", source: "Vedi la fonte del produttore", note: "La stima include un’allowance provvisoria per trasporto, dazi, adattamento, omologazione, riserva garanzia e IVA tedesca al 19%. Classificazione, dotazioni e certificazione possono modificare molto l’importo." },
} as const;

const models = [
  { name: "Qixing NC2124-R", type: "BEV · Star Future", image: "/hero.png", battery: "88.8 kWh", range: "420 km CLTC", mass: "3,495 kg", seats: "4–6", estimate: "€88–115k", source: "https://www.qixing-rv.com/electrcity-rv/star-future-iveco-chassis-electricity-pop-top.html" },
  { name: "Star Future EV5030", type: "BEV · pop-top", image: "/catalog/interior-lounge.png", battery: "50.38 kWh", range: "310 km CLTC", mass: "3,060 kg", seats: "4–5", estimate: "€67–89k", source: "https://www.qixing-rv.com/electrcity-rv/star-future-ev5030-pop-top-electricity-rv.html" },
  { name: "Qixing DT2926-Y", type: "PHEV · longitudinal bed", image: "/catalog/interior-wetroom.png", battery: "30 kWh", range: "58 km electric · 1,090 km combined", mass: "4,495 kg", seats: "2–6", estimate: "€82–108k", source: "https://www.qixing-rv.com/electrcity-rv/dt2926-y.html" },
];

const specLabels = {
  en: ["Battery", "Range", "GVW", "Seats"], de: ["Batterie", "Reichweite", "zGM", "Sitze"], fr: ["Batterie", "Autonomie", "PTAC", "Places"], es: ["Batería", "Autonomía", "MMA", "Plazas"], it: ["Batteria", "Autonomia", "Massa", "Posti"],
} as const;
const interiorCopy = {
  en: ["Living space / lounge reference", "Sleep + wet-room reference"], de: ["Referenz Wohnbereich / Lounge", "Referenz Schlafen + Nasszelle"], fr: ["Référence espace de vie / salon", "Référence couchage + salle d’eau"], es: ["Referencia salón / espacio de vida", "Referencia cama + baño"], it: ["Riferimento zona living / lounge", "Riferimento letto + bagno"],
} as const;

export default function Home() {
  const [language, setLanguage] = useState<Language>("en");
  const [formStatus, setFormStatus] = useState<"idle" | "sending" | "sent" | "error">("idle");
  const t = copy[language];
  const catalog = catalogCopy[language];
  useEffect(() => { document.documentElement.lang = language; }, [language]);
  const handleSubmit = async (event: React.FormEvent<HTMLFormElement>) => {
    event.preventDefault();
    setFormStatus("sending");
    const form = event.currentTarget;
    const response = await fetch("/api/early-access", { method: "POST", body: new FormData(form) });
    setFormStatus(response.ok ? "sent" : "error");
    if (response.ok) form.reset();
  };

  return <main>
    <nav className="nav shell" aria-label="Primary navigation"><a className="wordmark" href="#top" aria-label="Northline EV home"><span>northline</span><i>EV</i></a><div className="nav-links"><a href="#catalog">{catalog.nav}</a><a href="#approach">{t.nav.approach}</a><a href="#vision">{t.nav.vision}</a><a className="nav-cta" href="#early-access">{t.nav.access}</a><div className="language-switcher" aria-label={t.nav.language}>{languages.map((item) => <button className={language === item.code ? "active" : ""} key={item.code} onClick={() => setLanguage(item.code)}>{item.label}</button>)}</div></div></nav>
    <section className="hero" id="top"><div className="hero-image" role="img" aria-label="Conceptual electric motorhome on a coastal road" /><div className="hero-overlay" /><div className="hero-content shell"><p className="eyebrow"><span className="signal" /> {t.hero.eyebrow} / 01</p><h1>{t.hero.titleA}<br /><em>{t.hero.titleB}</em></h1><p className="hero-copy">{t.hero.body}</p><a className="button button-light" href="#early-access">{t.hero.cta} <span>↗</span></a></div><div className="hero-note">{t.hero.noteA}<br /><span>{t.hero.noteB}</span></div><div className="scroll-cue"><span /> {t.hero.scroll}</div></section>
    <section className="signal-band" aria-label="Northline principles"><div className="shell signal-band-inner">{t.band.map((item, index) => <span key={item}><b>{String(index + 1).padStart(2, "0")}</b>{item}</span>)}</div></section>
    <section className="intro shell" id="vision"><p className="eyebrow dark">{t.vision.eyebrow} / 02</p><div className="intro-grid"><h2>{t.vision.titleA}<br /><em>{t.vision.titleB}</em></h2><div><p className="lead">{t.vision.lead}</p><p className="muted">{t.vision.body}</p></div></div></section>
    <section className="catalog" id="catalog"><div className="shell"><p className="eyebrow dark">{catalog.eyebrow} / 03</p><div className="catalog-heading"><h2>{catalog.titleA}<br /><em>{catalog.titleB}</em></h2><p className="catalog-intro">{catalog.intro}</p></div><div className="model-grid">{models.map((model) => <article className="model-card" key={model.name}><div className="model-image" style={{ backgroundImage: `url(${model.image})` }}><span>{model.type}</span></div><div className="model-body"><div className="model-title"><h3>{model.name}</h3><strong>{model.estimate}</strong></div><p className="estimate-label">{catalog.estimate} · incl. VAT</p><div className="spec-grid"><span><b>{model.battery}</b>{specLabels[language][0]}</span><span><b>{model.range}</b>{specLabels[language][1]}</span><span><b>{model.mass}</b>{specLabels[language][2]}</span><span><b>{model.seats}</b>{specLabels[language][3]}</span></div><a className="source-link" href={model.source} target="_blank" rel="noreferrer">{catalog.source} <span>↗</span></a></div></article>)}</div><p className="catalog-note">{catalog.note}</p></div></section>
    <section className="dark-section" id="approach"><div className="shell"><p className="eyebrow">{t.approach.eyebrow} / 03</p><h2>{t.approach.titleA}<br /><em>{t.approach.titleB}</em></h2><div className="pillar-grid">{t.approach.pillars.map((pillar, index) => <article className="pillar" key={pillar.title}><span>{String(index + 1).padStart(2, "0")}</span><h3>{pillar.title}</h3><p>{pillar.copy}</p></article>)}</div></div></section>
    <section className="interiors shell"><div className="interiors-heading"><p className="eyebrow dark">Inside the idea / 04</p><p className="interior-note">{catalog.reference}</p></div><div className="interior-grid"><figure><div className="interior-image interior-lounge" /><figcaption>{interiorCopy[language][0]}</figcaption></figure><figure><div className="interior-image interior-wetroom" /><figcaption>{interiorCopy[language][1]}</figcaption></figure></div></section>
    <section className="manifesto shell"><div className="manifesto-mark">N<span>/</span>L</div><div><p className="eyebrow dark">{t.building.eyebrow} / 05</p><h2>{t.building.titleA}<br /><em>{t.building.titleB}</em></h2><p className="lead">{t.building.lead}</p><p className="muted">{t.building.body}</p><a className="text-link" href="#early-access">{t.building.link} <span>↗</span></a></div></section>
    <section className="early-access" id="early-access"><div className="shell early-grid"><div><p className="eyebrow">{t.access.eyebrow} / 06</p><h2>{t.access.titleA}<br /><em>{t.access.titleB}</em></h2><p className="early-copy">{t.access.body}</p></div><div className="access-card"><p className="card-label">{t.access.label}</p><p className="card-copy">{t.access.card}</p><form className="real-form" onSubmit={handleSubmit}><input type="email" name="email" required placeholder={t.access.field} aria-label={t.access.field} /><button type="submit" disabled={formStatus === "sending"}>{formStatus === "sending" ? "…" : t.access.button} <span>↗</span></button></form>{formStatus === "sent" && <p className="form-message">Thanks — we’ll be in touch.</p>}{formStatus === "error" && <p className="form-message">Please try again later.</p>}<p className="privacy">{t.access.privacy}</p></div></div></section>
    <footer className="footer shell"><a className="wordmark" href="#top"><span>northline</span><i>EV</i></a><p>{t.footer}<br />{t.status}</p><div className="footer-links"><a href="#catalog">{catalog.nav}</a><a href="#vision">{t.nav.vision}</a><a href="#approach">{t.nav.approach}</a><a href="#early-access">{t.nav.access}</a></div></footer>
  </main>;
}
